steps:

- id: Build WRF
  name: 'hashicorp/packer'
  args: ["build",
        "-force",
        "-var","project_id=$PROJECT_ID",
        "-var","zone=$_ZONE",
        "-var","image_name=${_IMAGE_NAME}",
        "-var","subnet=${_SUBNETWORK}",
        "-var","source_image=${_SOURCE_IMAGE}",
        "-var","source_image_project=${_SOURCE_IMAGE_PROJECT}",
        './${_BUILD_FLAVOR}/packer.json']
  waitFor: ["-"]

substitutions:
    _ZONE : 'us-central1-f' # default value
    _SUBNETWORK : 'default'
    _SOURCE_IMAGE : 'fluid-slurm-gcp-compute-centos'
    _SOURCE_IMAGE_PROJECT : 'fluid-cluster-ops'
    _IMAGE_NAME: 'wrf-gcp-gcc-openmpi'
    _BUILD_FLAVOR: 'gcc-openmpi'

timeout : 14400s
