steps:

- id: Build WRF
  name: 'hashicorp/packer'
  args: ["build",
        "-force",
        "-var","project_id=$PROJECT_ID",
        "-var","zone=$_ZONE",
        "-var","image_name=wrf-gcp-${_COMPILER}-${_MPI}-${_MACHINE}",
        "-var","subnet=${_SUBNETWORK}",
        "-var","source_image=${_SOURCE_IMAGE}",
        "-var","source_image_project=${_SOURCE_IMAGE_PROJECT}",
        './builds/${_MACHINE}/${_COMPILER}/${_MPI}/packer.json']
  waitFor: ["-"]

substitutions:
    _ZONE : 'us-central1-f' # default value
    _SUBNETWORK : 'default'
    _SOURCE_IMAGE : 'fluid-slurm-gcp-compute-centos'
    _SOURCE_IMAGE_PROJECT : 'fluid-cluster-ops'
    _COMPILER: 'gcc'
    _MPI: 'openmpi'
    _MACHINE: 'generic'

timeout : 14400s
